name: buildfork
on:
 workflow_dispatch:
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v5.0.0
     - name: cache
       uses: actions/cache@4.3.0
       with:
         path: ~/.npm
         key: buildCache
     - run: npm ci
     - run: npm test -- --coverage
       env:
         CI: true
     - name: build
       run: npm run build
     - name: Upload build files
       uses: actions/upload-artifact@v3.1.0
       with:
         name: build
         path: build
     
      
     
      
